### ISSUE TITLE
Towers spawning at world spawn point

### ISSUE THREAD

**Issue by TheButterbrotMan** [SmartStreamLabs/Tower-of-Chambers#1]
**Description:**
I'm experiencing an issue with the Tower of Chambers mod (tower_of_chambers-25.38.FH-neoforge-1.21.1.jar) where a tower appears directly at the spawn point in almost every new world I create.

**Details:**
- **Mod Version:** tower_of_chambers-25.38.FH-neoforge-1.21.1.jar
- **Minecraft Version:** 1.21.1

Please investigate this issue, as it affects gameplay significantly. Thank you!

**Comment by SmartStreamLabs** [comment]
Hello TheButterbrotMan, this is indeed a bug and we are currently working on a fix.

Possible release: 10/31/2024.

Thank you for passing it on!

**Comment by SmartStreamLabs** [comment]
Fixed in patch:  27.40.HK.
